### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by raianand1991** [jmgorius/mlir-standalone-template#4] opened 2020-10-27 12:41 UTC
ninja: error: loading 'build.ninja': No such file or directory while trying to build

**Comment by jmgorius** [comment] 2020-10-27 14:49
Make sure that you follow the instructions in the *How to build* section of the README. This error is caused by the build files not being generated, so this is likely due to either a missing CMake invocation or the build command being launched in the wrong directory.

Closing since this isn't related to the contents of the repository.

**Closed by jmgorius** 2020-10-27 14:49 UTC
